### ISSUE TITLE
Too weak unused symbol underline hint color

### ISSUE THREAD

**Issue by realth000** [hardhackerlabs/theme-jetbrains#1] opened 2023-07-09 00:10 UTC
The underline color on unused imports/variables/functions is too hard to see:

![screenshot_20230709080313607](https://github.com/hardhackerlabs/theme-jetbrains/assets/59462104/971bfd4e-5b33-4672-bbd2-d147311f1bfd)

Not only occurs with rust, I think, at least dart is the same.

CLion version: 2023.1.4
HardHacker theme version: 0.2.2

**Comment by anson0370** [comment] 2023-07-24 03:53
I'm sorry for just seeing this now. I just tried to reproduce it but was not successful. Actually, I didn't add that underline wave in the theme, so I'm not sure why it appears in your display.

Here is my screenshot.

<img width="646" alt="image" src="https://github.com/hardhackerlabs/theme-jetbrains/assets/283559/8c959fed-059f-4ebb-b2b9-44ec7c10ae19">

However, I am using the IDEA Community, so I'm not sure if it's because of CLion. I will try downloading CLion and give it another try.

**Comment by anson0370** [comment] 2023-07-24 04:06
hello @realth000 .

<img width="589" alt="image" src="https://github.com/hardhackerlabs/theme-jetbrains/assets/283559/ddf69348-41fb-4044-8575-70b80cb29955">

I also tried to reproduce it in CLion, but was not successful. Perhaps you can help me check the configuration of "Editor -> Color Schema -> General -> Errors and Warnings -> Unused code" in the Settings.

**Comment by realth000** [comment] 2023-07-24 05:14
@anson0370 
![mmexport1690174844661.png](https://github.com/hardhackerlabs/theme-jetbrains/assets/59462104/e66ba9a9-7d6b-469e-b64b-6c27a8106eb2)

Seems it is the style of "weak warning".

I found that enabling linter will give the weak warning.

At least for rust, reproducing steps are:

1. Settings -> Languages & Frameworks -> Rust -> External Linters.
2. Select "Cargo check"(default) or "Clippy"
3. Check the "Run external linter to analyze code on the fly" checkbox and then apply.

 Maybe all lint rules causing "weak warning" may reproduce this underline.

**Comment by anson0370** [comment] 2023-07-24 06:50
@realth000 Nice catch!
I tried to handle the underline wave of this "Weak warning" by giving it the same color as "Unused code." I'm not sure if it's clear enough for you to see?

<img width="632" alt="image" src="https://github.com/hardhackerlabs/theme-jetbrains/assets/283559/07ac27bd-6b01-4c1d-963f-d822e188ea40">

**Comment by realth000** [comment] 2023-07-24 06:59
Thanks! Crystal clear ✨

**Comment by anson0370** [comment] 2023-07-24 07:24
I just submitted version 0.2.3, which includes this change. The review by Jetbrains may take some time, but once it is approved, you can update and try it.

I'm going to close this issue, feel free to reopen it if any problem.

**Closed as completed by anson0370** 2023-07-24 07:24 UTC
